apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-django-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-django-db
  template:
    metadata:
      labels:
        app: postgres-django-db
    spec:
      containers:
        - name: postgres
          image: postgres:12.16-bullseye
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: app
            - name: POSTGRES_USER
              value: app_user
            - name: POSTGRES_PASSWORD
              value: app_password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-django-db-service
spec:
  selector:
    app: postgres-django-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
